// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


function evenFibbo(number){
    numberList = [];
    let x = 1
    let y = 2
    numberList.push(x);
    numberList.push(y);
    for(let i=2; i<number ; i++) {
        let z;
        z = x + y 
        numberList.push(z);
        x = y
        y = z
    }
    let sumEven = 0
    for(let j=0; j<numberList.length; j++) {
        if(numberList[j] % 2 === 0) {
        sumEven += numberList[j];
        }
    }
    return sumEven;
}

module.exports = evenFibbo;

